apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcpsm-cluster-secret-store
spec:
  provider:
    gcpsm:
      projectID: openclaw-antonmishel-03460
      auth:
        workloadIdentity:
          clusterLocation: us-west1
          clusterName: vancity-lens-prod
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
