apiVersion: v1
kind: ServiceAccount
metadata:
  name: vancity-lens-api
  namespace: vancity-lens
  annotations:
    iam.gke.io/gcp-service-account: vancity-lens-gke-sa@openclaw-antonmishel-03460.iam.gserviceaccount.com
