# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket         = "openclaw-antonmishel-03460-tf-state"
    encryption_key = null
    prefix         = "terragrunt/environments/staging"
  }
}
